[format]
quote-style = "double"
line-ending = "auto"

[lint]
# Enable pyflakes (`F`) and a subset of the pycodestyle (`E`) rules.
select = ["E4", "E7", "E9", "F"]
ignore = []

# Allow unused variables when they start with `_`.
allow-unused-variables = false

[lint.flake8-tidy-imports]
ban-relative-imports = "all"
